### ISSUE TITLE
Repo activity

### ISSUE THREAD

**Issue by jojolepro** [PsichiX/raui#1]
Hi! I'm considering to use your crate as a replacement for the current ui layouting system we have in the amethyst engine. I have a couple of questions before I attempt the migration though.
Is this crate still active?
Is there any bugs/missing features?

Thanks!

**Comment by PsichiX** [comment]
Hi! Sorry for long time response - i went for vacations, now i'm back and ready to answer your questions :)
Crate is active but not actively developed - if you want to be part of development team, we can give you repo write access to help improve whatever you want (i had plan to start improvements development in early 2019).
Things to implements for now are few:
- Passing arguments to signals;
- More generalized device events (to include devices such as touch, pen, generally make specialized devices input receivers based on some general device representation ready for implement by user).
- Custom events (still not sure if they will be ever needed, because this may be a part of previous feature)?

**Comment by PsichiX** [comment]
total rewrite of the crate
