### ISSUE TITLE
[Question] What's the Difference Between Props and Shared Props?

### ISSUE THREAD

**Issue by zicklag** [PsichiX/raui#13]
I could probably figure it out with enough investigation, but I haven't seen a solid pattern to it yet so I thought I'd just ask. :)

**Comment by PsichiX** [comment]
props are data explicitly passed down the tree of components, while shared props are implicitly passed data.
for example: you make a theme props data and want it to be accessible by all Material widgets (from raui-material` crate) used in your tree, so to not clone these props we just put them in shared props, by that we add or replace props that are accessible by al branches down the tree starting from the place these props were applied to shared props space.
we don't mix shared props with regular props bc they are implicit, you might not use them in your widget but some other widgets you pass as children of your might want to use them so instead of forcing your widget to clone all regular props to the children, these children components are gonna use shared props.
in-game example shows how it works in practice.
if you have more questions, i'll be happy to expand the explanation :)

**Comment by zicklag** [comment]
Ah, OK, that makes sense. That was the impression I got, but I wasn't sure what the scope of the shared props was. That makes sense. :+1:
